### PR TITLE
add using localStorage (browser feature) for web configuration

### PR DESCRIPTION
**Pull request by torei**
prevents latency on switching slider to selector and hiding sections

### CODE REVIEW

**Comment by torei** [comment]
known issue: clients keep their config when updating the web config from a different client

**Comment by torei** [comment]
fixed :]

**Comment by visualapproach** [comment]
very good job! Thx. If you have it in you, you are welcome to do the 4 wire also. A lot of work ofc, and a little less motivating if you don't own a 4-wire version, I understand that.

**Comment by torei** [comment]
no worries, will update the 4-wire as well :-)

**Pull request merged**
