### PR TITLE
add control selector and some fresh web ui styles

### PR DESCRIPTION
**Pull request by torei**
i couldnt keep my hands off it...

new menu for web ui adjustments
grafik

new slider style
grafik

brand new selector
grafik

heater is active
grafik

heater is enabled but inactive
grafik

simple "is not 1" a.k.a. 1.337 day(s) shortener :D
grafik

changed tooltip style
image

### CODE REVIEW

**Comment by torei** [comment]
this is only for the 6-wire .. yet

**Comment by torei** [comment]
converted to draft.
found an issue with the value of the temperature selector.
its not updating when setting the target from another source (mqtt, cmdqueue)

**Comment by visualapproach** [comment]
Yes, I don't remember how I handled that but IIRC it only updates once at load. But check in the websockets file

**Comment by torei** [comment]
yea, i have some hidden value fields commented out. thought i wouldnt need them.
guess i will do some work on that later to proper update the slider/selector values.
also want to enable the input field for the selector so that you can just enter a value from your keyboard

**Comment by torei** [comment]
@visualapproach 
what about the rest, any comments, suggestions?

**Comment by visualapproach** [comment]
I haven't had a chance to check yet, since I'm just home long enough to repack my bags between a bunch of journeys. Expect to have more time over Xmas

**Comment by torei** [comment]
so, this should be fine now

**Comment by visualapproach** [comment]
Did you undraft this PR? Can't see it from the phone...

**Comment by visualapproach** [comment]
> @visualapproach what about the rest, any comments, suggestions?

Played around a little now, and it is nice. There is one issue, which existed before, but is more pronounced with the new selectors. When changing the target temp by more than a few degrees there is a conflict between the inputs and the reported state. The value updates to the ACTUAL target temp while trying to set it. When thinking about it, I think that's why I only updated the slider at page loading, and not after. I suggest doing the same with the selector thingies. Then, it will be set once, and you can fiddle with it without it changing, and you can see the resulting target temp in the topmost section. If you then change target temp from another device, the selector/slider won't update, but I think that's a better situation.

Also, when following your steps above I managed to reboot the ESP by clicking too quickly on "increase temp".

**Comment by visualapproach** [comment]
The rebooting isn't caused by your html I think. It reports last reboot cause "software/system restart". Need to check that out as well...

**Comment by visualapproach** [comment]
One more thing: On loading the main page the sliders are showing before switching to selectors after a few seconds.

**Comment by torei** [comment]
yea, about the "actual temp" update while using the selector..
same issue i had with the input fields. for those, javascript is blocking an update on the "active" input fields
`if (document.activeElement !== elemSelectorTemp) elemSelectorTemp.value = msgobj.TGT;`
so its not updating to "3" when typing in "38". you have to hit <enter> or activate a different element.

the latency of the js on the main page is annoying. had some ideas but didnt try them all - but i will do

**Comment by visualapproach** [comment]
maybe set a timer to 3 seconds or so each time a control is changed by the user. After timer reaches zero it send the request?

**Comment by torei** [comment]
exactly what i was thinking about. also the button is selected, maybe i can somehow unselect it.

what about the reboot? i dont get it. you accidentally click the item from the menu?

**Comment by visualapproach** [comment]
If you send too many commands in a short time, by pressing for instance "brightness UP" button like crazy, the ESP will restart. I thought I found the bug but no luck yet. It's my problem though so you don't need to think about it.

**Pull request merged**
