### PR TITLE
Updated Home Assistant yaml-files

### PR DESCRIPTION
**Pull request by Skeletorjus**
MQTT-entities moved to package, added instructions

~~Added unique_id so entities can be changed from UI~~
~~Consistent use of capitalization~~

### CODE REVIEW

**Comment by chunkysteveo** [comment]
cool. Didn't know things added via yaml could then be altered via the UI.

**Comment by Skeletorjus** [comment]
It's a great feature, allows you to easily override name, entity_id, icon, and assigned area.

I was also thinking of combining everything to a single package for Home Assistant (no separate file for every entity type) as I feel it would simplify setup a lot, but I'm not sure if that would go against any previous decisions you've made about the file structure.

**Comment by chunkysteveo** [comment]
I'd probably leave the structure as it is, as there are multiple ways multiple people set HA up. I think the preferred method is to have everything segmented into their own custom folder structure, But I am still a crazy person with a HUUUGE config.yaml file that I just search up and down(!)

For the sake of example entities, I think the current setup is fine.

I'd love to see someone who knows HA provide assistance with making the mqtt an MQTT Device, so we can have a physical MQTT device, with the entities for it. It has something to do with setting up a device ID and class info, and linking all the entities to it, but I haven't had time to try it out. Would be useful to have that so auto-discovery would just pick up all the available entities.

**Comment by chunkysteveo** [comment]
Packages... that's the thing I had in my mind! I'd be up for an upgrade on the structure with a readme file in the directory to explain what to do. That would help me out too, to get things right!!

**Comment by Skeletorjus** [comment]
> Packages... that's the thing I had in my mind! I'd be up for an upgrade on the structure with a readme file in the directory to explain what to do. That would help me out too, to get things right!!

Alright, I created a package file including all the sensors, switches and buttons, and added instructions.
Hopefully the instructions are easy to follow.
Also included https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/discussions/52 by @sjeffrey101 (climate control).

**Comment by sjeffrey101** [comment]
@Skeletorjus  please see this post, i have a thermostat working much better without the need for the automation.
[https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/135#issuecomment-974844063](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/135#issuecomment-974844063)

**Comment by Skeletorjus** [comment]
> @Skeletorjus please see this post, i have a thermostat working much better without the need for the automation. [#135 (comment)](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/135#issuecomment-974844063)

Thanks a bunch, amazing work!
All the information is so fragmented right now, makes it hard to get a good overview. Hopefully this will help.

**Comment by sjeffrey101** [comment]
> All the information is so fragmented right now, makes it hard to get a good overview. Hopefully this will help.

yes, im not sure why additional homeassistant threads were create rather than going on my original one.  But this will make it much clearer.  Maybe the existing HA threads need closing and a new one creating, to discuss going forward and keeping on a single thread. this is a great addition.

would be great to get it as a device!

**Comment by visualapproach** [comment]
@Skeletorjus thank you. Merged now. Looks nice!

**Pull request merged**
