### PR TITLE
all the latest changes for the 4-wire

### PR DESCRIPTION
**Pull request by torei**

### CODE REVIEW

**Comment by visualapproach** [comment]
did "tttt" not work or did you dislike it? Both is also a valid combo...

**Comment by torei** [comment]
uhm.. it wasnt available in the html/js and also not in the BWC? or did i miss something

**Comment by visualapproach** [comment]
> uhm.. it wasnt available in the html/js and also not in the BWC? or did i miss something

If I bothered to check before asking... Feat not implemented in 4-wire. Doable, but do people really need it? It's kinda inaccurate anyway

**Comment by torei** [comment]
i have bugs on that in my environment. still want to check that but i really dont need it. i count 1 hour with +2°C

**Comment by visualapproach** [comment]
how does the bug show?

**Comment by torei** [comment]
kind of.. crazy

image

**Comment by visualapproach** [comment]
Okay, actually I don't consider it a bug per se. It calculates where the temperature curve (if it where a straight line) hits the target temperature line. In case of falling temperature below the target, the curves diverge and will never cross. The crossing occured in the past. Hence negative values. Due to some lag the calculation can look crazy before it gets a couple of consistent readings.

**Comment by chunkysteveo** [comment]
Ohh is tttt the time to target temp?? I'd like that in the 4 wire code 🙏

**Comment by torei** [comment]
> Ohh is tttt the time to target temp?? I'd like that in the 4 wire code pray

NOOOO :D

**Comment by visualapproach** [comment]
sorry @torei , I updated again after your merger. Now with your beloved tttt and more updates of states.

**Comment by torei** [comment]
lulz. ok. will enable the tttt html stuff tomorrow :-)

**Comment by torei** [comment]
@chunkysteveo anything else? :D

**Pull request merged**
