### PR TITLE
Added support for prometheus metrics

### PR DESCRIPTION
**Pull request by svanscho**
see: https://prometheus.io/

```
user@machine % curl http://<layzspa-ip>/metrics

# HELP layzspa_info Metadata about the device.
# TYPE layzspa_info gauge
# UNIT layzspa_info
layzspa_info{version="2022-04-11",name="layzspa",chipid="xxxxxxx"} 1
# HELP layzspa_temperature_celcius Water temperature.
# TYPE layzspa_temperature_celcius gauge
# UNIT layzspa_temperature_celcius °C
layzspa_temperature_celcius 0
# HELP layzspa_target_temperature_celcius Water target temperature.
# TYPE layzspa_target_temperature_celcius gauge
# UNIT layzspa_target_temperature_celcius °C
layzspa_target_temperature_celcius 0
# HELP layzspa_heater_state Heater state.
# TYPE layzspa_heater_state gauge
# UNIT layzspa_heater_state
layzspa_heater_state 0
# HELP layzspa_pump_state Pump state.
# TYPE layzspa_pump_state gauge
# UNIT layzspa_pump_state
layzspa_pump_state 0
# HELP layzspa_jets_state Jets state.
# TYPE layzspa_jets_state gauge
# UNIT layzspa_jets_state
layzspa_jets_state 0
# HELP layzspa_bubbles_state Bubbles state.
# TYPE layzspa_bubbles_state gauge
# UNIT layzspa_bubbles_state
layzspa_bubbles_state 0
# HELP layzspa_power_state Bubbles state.
# TYPE layzspa_power_state gauge
# UNIT layzspa_power_state
layzspa_power_state 0
# HELP layzspa_locked_state Locked state.
# TYPE layzspa_locked_state gauge
# UNIT layzspa_locked_state
layzspa_locked_state 0
# HELP layzspa_unit_state Unit state.
# TYPE layzspa_unit_state gauge
# UNIT layzspa_unit_state
layzspa_unit_state 0
```

image

### CODE REVIEW

**Comment by svanscho** [comment]
@visualapproach made this PR to be able to read out gauges for my prometheus monitoring solution. Could also move this under a conditional compiler directive

**Comment by visualapproach** [comment]
Thank you! Can you make the PR to the development branch instead please.

**Comment by svanscho** [comment]
No worries. Here you go.

**Comment by visualapproach** [comment]
Super, I'll handle this when I can

**Pull request merged**
