### PR TITLE
datazip should be transient

### PR DESCRIPTION
**Pull request by jamesonuk**
Try again....
Datazip should be transient and removed after building.
If it is left in place you can end up with out of sync files being loaded.

If you want to keep the files for debugging you can comment out the last line of Code\gzip_littlefs.py

I will take a look at the other thing you mentioned as that shouldn't be too difficult I don't think

### CODE REVIEW

**Comment by visualapproach** [comment]
Lets discuss a proper and convenient workflow. First I'll describe how the code works now:
When user opens the web page "check firmware update" the ESP connects to github and reads the file ...fw/version.txt
Then it downloads all the datafiles *from github*. I don't want the ESP to download uncompressed files, so therefore I need to upload both the compressed and the uncompressed versions of the datafiles. Or so I believe.
After the files has been downloaded to LittleFS on the ESP it downloads .../fw/firmware.bin and reboots with new firmware. It skips this part if the version string is the same as in versions.txt.

There is a manual part of this that can lead to out of sync files, as you say. But the alternative would be me uploading the compressed files "manually" which will also lead to mistakes I guess.

Any good ideas how to handle this?

**Comment by jamesonuk** [comment]
Penny has dropped.   This is about updates.    Never considered that....  (Is it new in v4?)
I do have an idea though which is possibly more appropriate on the other PR

**Comment by visualapproach** [comment]
Yes it's new from v4.1. Sounds good :-)

**Comment by visualapproach** [comment]
update buttons removed

**Pull request closed without merging**
