### PR TITLE
fix selector value updates

### PR DESCRIPTION
**Pull request by torei**
from discussion
#414

### CODE REVIEW

**Comment by visualapproach** [comment]
That's fast :) I'll check soon

**Comment by torei** [comment]
but i did it a different way with state flags.
if its a problem with that reset on many commands, i think we should switch to the timer idea.
i think when changing for example from 20°C to 40°C, people should use the textfield. maybe some info tooltip about that would be nice

**Comment by visualapproach** [comment]
It is much better now. The tooltip idea is good - I didn't see that option. I know what's causing the resets now. It's saving the command queue twice on every click, and it chokes the filesystem. I'm working on a fix on the code side instead.

**Comment by torei** [comment]
nice, good to hear

**Pull request merged**
