### PR TITLE
Set build date

### PR DESCRIPTION
**Pull request by jamesonuk**
Not sure it is ready quite yet but this will update FW_VERSION config.h to the current date time

I might suggest that it could be better to include git branch and commit in there else the date isn't too helpful to debug anything if someone reports an issue with a version they have built.

Also I am not sure if there is a better was of doing this so that git doesn't think that config.h has always been updated.
My C++ knowledge is very lacking but if there a way to do this using environment variables or something that would mean the code is static but would change at compile time?

### CODE REVIEW

**Comment by visualapproach** [comment]
About the code at build time - yeah, I tried that with an environment variable. It worked but then people would all have their own "version" and when updating through the web page it would always find a different version and update. Doh, how hard can it be LOL

**Comment by jamesonuk** [comment]
As per other thread I think the issue is trying to combing source control and releases.

I think you want to look at releases that include the binary firmware and zipped file system contents and not just the source
Then when you build from source control and bump your versions you could include a git commit in the build and not just the date    Doing something like this would allow you to easily identify official releases vs people who have built it themselves.

Will have a look at how you can automate that as it should be possible to add the artefacts when you create the release and programmatically check for firmware updates).    Not sure if there is a better way of performing updates or not but this would at least separate the source code from the binaries and give you true static releases

**Comment by visualapproach** [comment]
> @visualapproach how are you creating your releases currently?

I have development branch checked out. 
Edit code. 
When happy
Edit config.h with a new fw date
Build file system to get the .gz files and the "filelist.txt" file updated.
Build project then copy firmware.bin from "nodemcuv2/" to "fw/". (This file now has the fw date hardcoded in it.)
Edit "fw/version.txt" with the same date as in "config.h".
Stage changes, which now includes all the "new" .gz files, firmware.bin etc.
Write a comment about the change.
Sync to github dev branch.

If I now want to propagate the new version into master, I make a PR dev->master. After that I (may) make a new release.

**Comment by jamesonuk** [comment]
Sorry I meant github releases https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/releases

**Comment by visualapproach** [comment]
Oh, I press "Draft a new release" and create a new tag and name, like v4.1.1 and select auto generate description. Did that answer your question?

**Comment by visualapproach** [comment]
Don't ask me where the "assets" came from in the last release 😄

**Comment by jamesonuk** [comment]
> Oh, I press "Draft a new release" and create a new tag and name, like v4.1.1 and select auto generate description. Did that answer your question?

Yes 😄 
What you probably should be looking to do in terms of distributing binaries is to add them as assets.   I think it will add source code by default as you have seen but there is a section where you can drag files to add.

Simplest solution would be just just add a zip of the filesystem and firmware files to the release that way.
You can then do something like call https://api.github.com/repos/visualapproach/WiFi-remote-for-Bestway -Lay-Z-SPA/releases/latest which will then show you the latest release with URLs for any assets.   This is just the latest non pre-release build (take out latest from the URL and I think you get the latest 30 releases)

I guess part of this depends on how you want to allow OTA updates like this.   If you only want people to be able to update to official releases this way then the latest URL is great.   If you want to allow people to sign up to dev branch then it gets a bit more complicated but just extends the same theory.

This can all be automated though and I would actually look at using GitHub actions.   It isn't too complicated to have an action triggered on merge of PR to master that would 
- Update version to next one (plenty of free actions already built for this and there will be one that should handle C++ I imagine)
- Commit version bump
- Create version tag
- Create release for version tag with firmware binary and filesystem zip attached

You can go even further and say a PR to DEV-release or similar does the above but creates a pre-release (or even nightly) release.   That would mean you probably want to have a gold dev branch  and do actual development in branches off this.

**Comment by visualapproach** [comment]
Thanks for those points! Why are there only 24 hours each day? Phew, a bit overwhelmed but I guess I need to check it out. But I'll prioritize getting some issues sorted with the code. Specifically using less memory. Down a couple of kB DRAM by picking some low hanging fruits for the moment.
Thanks again, I'll call you back with questions no doubt!

**Comment by jamesonuk** [comment]
Ultimately you can do this with little change to what you are doing now.
When you want to create a github release just do what you are doing now but just drag and drop the firmware.bin and a the zipped up filesystem as binaries rather than adding them to the git repository.

Then when you are checking for a new version just go to https://api.github.com/repos/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/releases/latest and parse the JSON to see what the latest release is.

In order to make this work though you will want to change the firmware version from a date to the actual version tag (ie. v4.1.1 now).   Then you compare the firmware version of the current firmware and the one returned in the JSON above.   If it is newer you can download the artefacts and then other than unzipping the filesystem the actual update code should be as you have now.

You can look at automating it later.

**Comment by visualapproach** [comment]
update buttons removed due to memory limitations on the 8266

**Pull request closed without merging**
