### PR TITLE
Add Restart Button to HA

### PR DESCRIPTION
**Pull request by chunkysteveo**
Add a new Home Assistant "Restart Device Class" button for the ESP. Uses device_class to correctly set button to restart icon in front-end. Triggers CMD 6.

### CODE REVIEW

**Comment by visualapproach** [comment]
Please make the PR to the development branch. Thank you

**Comment by chunkysteveo** [comment]
ah yeah sorry - forgot!!!

**Comment by chunkysteveo** [comment]
Done @visualapproach

**Comment by visualapproach** [comment]
Thanks :)

**Pull request merged**
