### PR TITLE
Added Filtertimer and extra Options for Chlorine and Filter

### PR DESCRIPTION
**Pull request by Bankaifan**
Hi,

I made some small enhancements for my needs.

Added a Filtertimer besides the Chlorine timer, since I REALLY can use this. Always forget to clean/change my filters.
Added the ability to customize the chlorine and filter interval (The days, till the Buttons turn red)
This is my first time working with github (besides downloading) and so my first fork/pull request. If I have to do/change anything, tell me :)

If me english is too bad - sorry, I can switch and use a translator

PS: Not sure why github shows those html-files as if i created them completely new

2020-11-28_16h29_31
2020-11-28_16h29_38

### CODE REVIEW

**Comment by visualapproach** [comment]
Hi @Bankaifan (Amusing alias. In Swedish: "smash in the devil" 😃 )
Please, no translator! Your English is perfectly fine, as far as an old fart from Sweden can tell.
I like your expansion and I'm willing to merge. But I think _fint/_clint and _finterval/_clinterval is redundant. As far as I can tell, you should be fine using just one interval variable per timer and not "update" _fint = _finterval every loop.  Or do I misunderstand the intention?
Otherwise it looks perfect.

**Comment by Bankaifan** [comment]
Haha didn't know that. Got it from a Manga :)

And thanks! You are right. To be honest, my times as a programmer are long gone. Those where the first lines of code since about 8 Years and then it was just C#. So I tried to orientate on your variables price and cost. 
Started with _finterval/_clinterval which didn't work. Then went to this variant. But I will give it a try and look if I can reduce it. 
Greetings to sweden from germany :) I plan to visit sweden since years. I like the nature up there :)))

**Comment by visualapproach** [comment]
I merged now, and I'll fix the redundancy and test that it works.
Thanks for your effort!

Thanks, Lets hope for better times so we can travel again.

**Comment by visualapproach** [comment]
@Bankaifan It appears to work fine now. I basically just replaced _fint with _finterval and removed the updates from updatetimes(). Then I updated also the other example with your new html/.js. I did change back timeout(loadcmd, 2000) to interval(...) because occasionally it doesn't update and then you don't know if the command went through or not. (I tried exactly that) Just so you know. You can ofc keep it as is on your fork :-). Cheers

**Pull request merged**
