### PR TITLE
updates on HTML and JS

### PR DESCRIPTION
**Pull request by torei**

### CODE REVIEW

**Comment by torei** [comment]
thought i could add the 4-wire changes here as well.. but there are so many differences.. wth is godMode? :D
will start with the main code at the 4-wire and then update the data folder for it. to be continued..

**Comment by chunkysteveo** [comment]
Cool! 

God Mode is when we have to take control of the unit to manage it. I wish I had a 6 wire unit, 😫😭

Would be good to remove things visible in the 4 wire version and get it up to speed with the 6 wire version.

**Comment by torei** [comment]
@visualapproach if you like to, you can merge this
the 4-wire changes are mentioned here #177

**Comment by visualapproach** [comment]
Thanks @torei

**Pull request merged**
